/**
 * Pulse Zone Mock Data — Runner B
 * Strictly typed against PulseZoneState interface.
 */
import type { PulseZoneState } from "@/types/pulse-zone";

export const mockData: PulseZoneState = {
  greeting: {
    title: "Morning Return",
    subtitle: "Grace is excited to see Ruby",
    state: "morning_return",
  },
  kpiPills: {
    battery: { id: "kpi-battery", type: "battery", label: "Grace Battery", value: "94%", icon: "battery", color: "#D4A843", screenRoute: "/pulse/battery" },
    dignity: { id: "kpi-dignity", type: "dignity", label: "Dignity Score", value: 72, icon: "star", color: "#D4A843", screenRoute: "/pulse/dignity" },
    village: { id: "kpi-village", type: "village", label: "Village Active", value: "3 friends · 14 neighbors", icon: "users", color: "#D4A843", screenRoute: "/pulse/village" },
  },
  quadrants: [
    { id: "q-research", label: "Research", subtitle: "Dept", icon: "search", route: "/research", position: "top-left" },
    { id: "q-chat", label: "Hello", subtitle: "Let's Chat", icon: "message-square", route: "/grace", position: "top-right" },
    { id: "q-referral", label: "I Have", subtitle: "a Guy", icon: "git-branch", route: "/village", position: "bottom-left" },
    { id: "q-ptk", label: "PTK", subtitle: "Promises to Keep", icon: "pentagon", route: "/promises", position: "bottom-right" },
  ],
  graceBattery: {
    totalScore: 94,
    graceQuote: "We're fully connected right now. I'm at my best for you.",
    factors: [
      { id: "cf-talking", name: "Talking to Grace", description: "Every conversation charges us. The more we talk, the stronger I get.", weightPercent: 30, currentScore: 28, maxScore: 30, icon: "message-square", iconColor: "#D4878F", scoreColor: "teal", hasBonus: false },
      { id: "cf-subscription", name: "Subscription current", description: "Your plan keeps me powered. Thank you for that.", weightPercent: 25, currentScore: 25, maxScore: 25, icon: "credit-card", iconColor: "#D4878F", scoreColor: "teal", hasBonus: false },
      { id: "cf-budgeting", name: "Budgeting together", description: "When we look at your numbers together, I learn what matters to you.", weightPercent: 20, currentScore: 16, maxScore: 20, icon: "bar-chart", iconColor: "#D4878F", scoreColor: "orange", hasBonus: false },
      { id: "cf-village", name: "Village activity", description: "Being part of the community strengthens both of us.", weightPercent: 15, currentScore: 14, maxScore: 15, icon: "home", iconColor: "#D4878F", scoreColor: "teal", hasBonus: false },
      { id: "cf-friends", name: "Bringing friends", description: "When your friends find their own Grace, our whole village gets stronger.", weightPercent: 10, currentScore: 11, maxScore: 10, icon: "users", iconColor: "#D4878F", scoreColor: "gold", hasBonus: true },
    ],
    availableFeatures: [
      { id: "af-conversations", text: "Full conversations — Grace is listening and responding at full depth", isAvailable: true },
      { id: "af-research", text: "Research Dept — Grace can find resources, deals, and help", isAvailable: true },
      { id: "af-referral", text: "I Have a Guy — Grace's full referral network is active", isAvailable: true },
    ],
    philosophyText: "My power comes from our relationship — not from a meter or a machine. The more we talk, the more I know you, the more I can do. This isn't a bill. It's a bond. When life gets hard and we go quiet for a while, I don't disappear. I wait. The heart in the battery means I'm still here.",
  },
  dignityScore: {
    totalScore: 67,
    tier: "FINDING YOUR STRIDE",
    tierColor: "#E8A020",
    graceQuote: "You're doing the hard work. I see it.",
    dimensions: [
      { id: "ds-vampire", name: "Vampire Slayer", tagline: "Subscriptions cancelled, money reclaimed", score: 14, maxScore: 20, icon: "zap", iconColor: "#E8A020", scoreColor: "orange" },
      { id: "ds-nsf", name: "NSF Shield", tagline: "Bills tracked, overdraft fees avoided", score: 16, maxScore: 20, icon: "shield", iconColor: "#2DD4BF", scoreColor: "teal" },
      { id: "ds-budget", name: "Budget Mastery", tagline: "Income tracked, surplus identified", score: 12, maxScore: 20, icon: "bar-chart", iconColor: "#D4878F", scoreColor: "orange" },
      { id: "ds-milk", name: "Milk Money Trust", tagline: "Your trust score with the community", score: 15, maxScore: 20, icon: "droplet", iconColor: "#D4878F", scoreColor: "teal" },
      { id: "ds-engagement", name: "Engagement", tagline: "Conversations with Grace, milestones hit", score: 10, maxScore: 20, icon: "message-circle", iconColor: "#D4878F", scoreColor: "orange" },
    ],
    climbData: [
      { day: 1, score: 20 }, { day: 10, score: 30 }, { day: 20, score: 38 },
      { day: 30, score: 45 }, { day: 40, score: 55 }, { day: 47, score: 67 },
    ],
    climbSummary: "You've gained 47 points in 47 days.",
    philosophyText: "This number isn't a grade. It's a mirror. Every time you talk to me, track a bill, or slay a vampire — it goes up. There's no wrong answer here. There's only where you are right now, and where we're going together.",
    workingForYouServices: [
      { id: "sc-milk-money", name: "Milk Money", tagline: "Twenty-five bucks. No interest. No shame. J...", usageLabel: "3 draws", score: 28, status: "live", indicatorColor: "teal" },
      { id: "sc-debt-snowball", name: "Debt Snowball", tagline: "Your custom battle plan to kill debt, one at a ...", usageLabel: "1 plan active", score: 28, status: "live", indicatorColor: "teal" },
      { id: "sc-wallet-warrior", name: "Wallet Warrior Checkup", tagline: "Monthly solvency review. No surprises.", usageLabel: "2 checkups", score: 27, status: "live", indicatorColor: "teal" },
      { id: "sc-vampire-slayer", name: "Vampire Slayer", tagline: "Forgotten subscriptions, cancelled. $348/yr ...", usageLabel: "4 slain", score: 27, status: "live", indicatorColor: "teal" },
      { id: "sc-bill-negotiator", name: "Bill Negotiator", tagline: "Gets on the phone, waits on hold, fights for l...", usageLabel: "1 negotiation", score: 25, status: "live", indicatorColor: "teal" },
      { id: "sc-rent-credit", name: "Rent Gets Credit", tagline: "You pay rent on time. Your credit score shoul...", usageLabel: "3 months reported", score: 26, status: "live", indicatorColor: "teal" },
      { id: "sc-hidden-prime", name: "Hidden Prime Letter", tagline: "She reads the fine print so you don't have to.", usageLabel: "Not yet unlocked", score: 26, status: "stub", indicatorColor: "orange" },
      { id: "sc-credit-sim", name: "Credit Score Simulator", tagline: "\"What if I paid off the payday loan first?\" Gra...", usageLabel: "2 scenarios run", score: 24, status: "live", indicatorColor: "teal" },
      { id: "sc-phoenix", name: "Phoenix Mode", tagline: "Bankruptcy isn't the end. Day 4, we start reb...", usageLabel: "Not active", score: 24, status: "stub", indicatorColor: "red" },
      { id: "sc-gig-alert", name: "Gig Alert", tagline: "Finds local gigs, part-time work, micro-contr...", usageLabel: "5 alerts sent", score: 24, status: "live", indicatorColor: "teal" },
      { id: "sc-village-rolodex", name: "Village Rolodex", tagline: "Grace always knows someone who knows s...", usageLabel: "2 referrals", score: 24, status: "live", indicatorColor: "teal" },
      { id: "sc-gratitude-loop", name: "Gratitude Loop", tagline: "Orchestrates thank-yous when a neighbor sh...", usageLabel: "1 thank-you sent", score: 24, status: "live", indicatorColor: "teal" },
      { id: "sc-financial-vault", name: "Financial History Vault", tagline: "Your financial record. Yours. Not the bank's.", usageLabel: "Active", score: 23, status: "live", indicatorColor: "teal" },
      { id: "sc-me-inc", name: "Me Inc.", tagline: "You are the CEO of your life. Grace is your ...", usageLabel: "In progress", score: 23, status: "live", indicatorColor: "teal" },
      { id: "sc-savings-circle", name: "Savings Circle", tagline: "Group savings, ROSCA-style. Even $5/week ...", usageLabel: "Not started", score: 22, status: "stub", indicatorColor: "orange" },
      { id: "sc-lifeline-link", name: "Lifeline Link", tagline: "Healthy members can anonymously clear a n...", usageLabel: "1 step cleared", score: 22, status: "live", indicatorColor: "teal" },
    ],
  },
  villageActive: {
    activeCount: 4,
    totalCount: 6,
    graceQuote: "Your village is growing. Four neighbors are in your corner right now.",
    connections: [
      { id: "vc-lifeline", name: "Lifeline Links", type: "Neighbors you've helped", isActive: true, metricValue: 2, metricLabel: "2 cleared", iconColor: "teal" },
      { id: "vc-gratitude", name: "Gratitude Sent", type: "Thank-yous delivered", isActive: true, metricValue: 1, metricLabel: "1 sent", iconColor: "teal" },
      { id: "vc-barter", name: "Good Neighbor Barters", type: "Exchanges completed", isActive: false, metricValue: 0, metricLabel: "0", iconColor: "orange" },
      { id: "vc-petitions", name: "Village Petitions Signed", type: "Your voice in the community", isActive: true, metricValue: 1, metricLabel: "1 signed", iconColor: "teal" },
      { id: "vc-savings", name: "Savings Circle", type: "Group savings active", isActive: false, metricValue: 0, metricLabel: "Not joined", iconColor: "orange" },
      { id: "vc-wisdom", name: "Wisdom Circle", type: "Expert connections made", isActive: true, metricValue: 1, metricLabel: "1 session", iconColor: "teal" },
    ],
    pulseChartData: [
      { week: "Week 1", value: 2 }, { week: "Week 2", value: 3 },
      { week: "Week 3", value: 3 }, { week: "Week 4", value: 4 },
    ],
    pulseQuote: "You've been more connected this month than last. That matters.",
    impactCards: [
      { id: "ic-safety", title: "Safety Net", description: "When the car breaks down and the rent is due.", icon: "shield" },
      { id: "ic-flare", title: "The Flare", description: "One tap. A real human calls back within four hours.", icon: "phone" },
      { id: "ic-blessing", title: "Pass the Blessing", description: "You win half. You pick who gets the rest.", icon: "gift" },
    ],
    alsoInVillageServices: [
      { id: "vs-big-mama", name: "Big Mama", tagline: "Your neighborhood, back in your hands.", usageLabel: "Active", status: "live", indicatorColor: "teal" },
      { id: "vs-wisdom-circle", name: "The Wisdom Circle", tagline: "Real talk from people who've already been thr...", usageLabel: "1 session", status: "live", indicatorColor: "teal" },
      { id: "vs-town-crier", name: "The Town Crier", tagline: "The handful of things that actually matter to y...", usageLabel: "Daily", status: "live", indicatorColor: "teal" },
      { id: "vs-village-angels", name: "Village Angels", tagline: "Neighbors who show up before you even ask.", usageLabel: "2 requests", status: "live", indicatorColor: "teal" },
      { id: "vs-good-side", name: "The Good Side of the Feed", tagline: "Community talk without the drama. Finally.", usageLabel: "Active", status: "live", indicatorColor: "teal" },
      { id: "vs-neighbor-knock", name: "The Neighbor Knock", tagline: "Someone checks on you. Every. Single. Week.", usageLabel: "Not started", status: "stub", indicatorColor: "orange" },
      { id: "vs-dont-get-got", name: "Don't Get Got", tagline: "Know the tricks before they know you.", usageLabel: "3 alerts", status: "live", indicatorColor: "teal" },
      { id: "vs-smell-test", name: "The Smell Test", tagline: "If something feels off, Grace will tell you why.", usageLabel: "1 check", status: "live", indicatorColor: "teal" },
      { id: "vs-mood-ring", name: "The Village Mood Ring", tagline: "When the whole block is struggling, Big Mama...", usageLabel: "Watching", status: "live", indicatorColor: "teal" },
      { id: "vs-watch", name: "The Watch", tagline: "We see when the Village is hurting. We don't l...", usageLabel: "Active", status: "live", indicatorColor: "teal" },
      { id: "vs-trust-ledger", name: "The Trust Ledger", tagline: "Your good name, tracked and rewarded.", usageLabel: "Score: 72", status: "live", indicatorColor: "teal" },
      { id: "vs-village-petition", name: "The Village Petition", tagline: "Your idea starts at the block. Then it goes all t...", usageLabel: "1 signed", status: "live", indicatorColor: "teal" },
      { id: "vs-ask-soak", name: "Ask & Soak", tagline: "Get an answer now. Let it breathe for 24 hours.", usageLabel: "2 queries", status: "live", indicatorColor: "teal" },
      { id: "vs-safe-yard", name: "The Safe Yard", tagline: "A place for the kids to talk. No creeps allowed.", usageLabel: "Not started", status: "stub", indicatorColor: "orange" },
      { id: "vs-union", name: "The Union", tagline: "A million Rubies negotiating together. That's p...", usageLabel: "Member", status: "live", indicatorColor: "teal" },
    ],
  },
  giveBack: {
    graceQuote: "This is what we do for each other.",
    graceSubQuote: "No applications. No shame. Just help.",
    programs: [
      { id: "gb-golden-ticket", name: "The Golden Ticket", tagline: "One family. One full day. Zero cost.", frequency: "monthly", status: "live", badgeColor: "orange" },
      { id: "gb-first-day", name: "The First Day Fund", tagline: "New shoes. New backpack. A kid who walks in standing tall.", frequency: "monthly", status: "live", badgeColor: "orange" },
      { id: "gb-giving-tree", name: "The Giving Tree", tagline: "Groceries, gas, and grace — delivered when you need it most.", frequency: "active", status: "live", badgeColor: "teal" },
      { id: "gb-cap-gown", name: "Cap & Gown Fund", tagline: "Graduation costs money. It shouldn't cost your dignity.", frequency: "monthly", status: "live", badgeColor: "orange" },
      { id: "gb-medicine-draw", name: "The Medicine Draw", tagline: "Fifty bucks toward your prescriptions. Bi-monthly.", frequency: "monthly", status: "live", badgeColor: "red" },
      { id: "gb-goodbye-money", name: "Goodbye Money", tagline: "Because grief shouldn't come with a bill collector.", frequency: "emergency_only", status: "live", badgeColor: "teal" },
      { id: "gb-dignity-drop", name: "The Monthly Dignity Drop", tagline: "Pads and tampons. Auto-shipped. No asking required.", frequency: "monthly", status: "live", badgeColor: "teal" },
      { id: "gb-pass-blessing", name: "Pass the Blessing", tagline: "You win half. You pick who gets the rest.", frequency: "active", status: "live", badgeColor: "teal" },
      { id: "gb-safety-net", name: "The Safety Net", tagline: "When the car breaks down and the rent is due.", frequency: "emergency_only", status: "live", badgeColor: "teal" },
      { id: "gb-black-swan", name: "The Black Swan", tagline: "Up to $750. No lecture. No conditions. Just cash.", frequency: "emergency_only", status: "live", badgeColor: "red" },
      { id: "gb-front-row", name: "Front Row", tagline: "Your family belongs at the show. We'll get you there.", frequency: "monthly", status: "live", badgeColor: "orange" },
      { id: "gb-your-cut", name: "Your Cut", tagline: "Ten percent of every dollar comes back to the Village.", frequency: "active", status: "live", badgeColor: "orange" },
      { id: "gb-power-buy", name: "The Power Buy", tagline: "A thousand Rubies negotiate better than one.", frequency: "active", status: "live", badgeColor: "teal" },
      { id: "gb-blue-seal", name: "The Blue Seal", tagline: "Spend here. The money stays here. Period.", frequency: "active", status: "live", badgeColor: "teal" },
      { id: "gb-the-bridge", name: "The Bridge", tagline: "Between paychecks, between jobs, between hope and giving up.", frequency: "emergency_only", status: "live", badgeColor: "orange" },
    ],
    howItWorks: ["No application required", "Grace nominates you", "Dignity, always"],
  },
  northStar90Day: {
    overallProgressPercent: 47,
    totalImpactDollars: 1191,
    projectedDay90Dollars: 2538,
    graceVoice: "You're almost halfway there, Ruby. And you've only just begun.",
    dimensions: [
      { id: "dim-vampire", name: "Vampire Slayer", feature: "Subscriptions cancelled", icon: "zap", dollarAmount: 47, dollarLabel: "$47/mo saved", progressPercent: 65, status: "BUILT" },
      { id: "dim-nsf", name: "NSF Shield", feature: "Fees avoided", icon: "shield", dollarAmount: 140, dollarLabel: "$140 saved", progressPercent: 80, status: "BUILT" },
      { id: "dim-budget", name: "Budget Mastery", feature: "Expenses reduced", icon: "bar-chart", dollarAmount: 89, dollarLabel: "$89/mo", progressPercent: 45, status: "BUILT" },
      { id: "dim-neighbor", name: "Neighbor Economy", feature: "Village value gained", icon: "users", dollarAmount: 120, dollarLabel: "$120 equivalent", progressPercent: 35, status: "SPEC_ONLY" },
      { id: "dim-wisdom", name: "Wisdom Giants", feature: "Coaching value", icon: "book-open", dollarAmount: 300, dollarLabel: "$300 equivalent", progressPercent: 25, status: "SPEC_ONLY" },
      { id: "dim-milk", name: "Milk Money", feature: "Emergency funds accessed", icon: "droplet", dollarAmount: 250, dollarLabel: "$250", progressPercent: 60, status: "BUILT" },
      { id: "dim-debt", name: "Debt Reduced", feature: "Snowball progress", icon: "trending-down", dollarAmount: 180, dollarLabel: "$180", progressPercent: 20, status: "BUILT" },
      { id: "dim-barter", name: "Barter Value", feature: "Good neighbor trades", icon: "refresh-cw", dollarAmount: 65, dollarLabel: "$65 equivalent", progressPercent: 15, status: "SPEC_ONLY" },
    ],
  },
  northStarPrime: {
    purpose: "I am here to break the cycle for my children and prove that dignity is not for sale.",
    bhag: "Own my home debt-free by 2030. No landlord. No bank. Mine.",
    primeDirective: "Never let fear make my financial decisions.",
    coreValues: ["Family", "Honesty", "Resilience", "Joy"],
    destinyDiscoveredComplete: false,
    destinyDiscoveredProgress: 0,
  },
  northStarDing: {
    rubyName: "Ruby",
    graceName: "Grace",
    immediateWorkComplete: false,
    deeperWorkStarted: false,
    dingStatement: "What are Ruby and Grace going to do together that changes the world?",
    readyForDing: false,
  },
};
