// Pulse Zone — Complete Mock Data
// Every number here is Ruby's story. Every service is a promise.

export const pulseData = {
  greeting: {
    title: "Morning Return",
    subtitle: "Grace is excited to see Ruby",
    state: "morning_return" as const,
  },
  kpiPills: {
    battery: {
      id: "kpi-battery",
      type: "battery" as const,
      label: "Grace Battery",
      value: "94%",
      icon: "battery-charging",
      color: "#D4A843",
      screenRoute: "RelationshipBattery",
    },
    dignity: {
      id: "kpi-dignity",
      type: "dignity" as const,
      label: "Dignity Score",
      value: 72,
      icon: "star",
      color: "#D4A843",
      screenRoute: "DignityScore",
    },
    village: {
      id: "kpi-village",
      type: "village" as const,
      label: "Village Active",
      value: "3 friends · 14 neighbors",
      icon: "users",
      color: "#D4A843",
      screenRoute: "VillageActive",
    },
  },
  quadrants: [
    { id: "q-research", label: "Research", subtitle: "Dept", icon: "search", route: "research", position: "top-left" as const },
    { id: "q-chat", label: "Hello", subtitle: "Let's Chat", icon: "message-square", route: "chat", position: "top-right" as const },
    { id: "q-referral", label: "I Have", subtitle: "a Guy", icon: "git-branch", route: "referral", position: "bottom-left" as const },
    { id: "q-ptk", label: "PTK", subtitle: "Promises to Keep", icon: "pentagon", route: "ptk", position: "bottom-right" as const },
  ],
  graceBattery: {
    totalScore: 94,
    graceQuote: "We're fully connected right now. I'm at my best for you.",
    factors: [
      { id: "cf-talking", name: "Talking to Grace", description: "Every conversation charges us. The more we talk, the stronger I get.", weightPercent: 30, currentScore: 28, maxScore: 30, icon: "message-square", iconColor: "#2DD4BF", scoreColor: "teal" as const, hasBonus: false },
      { id: "cf-subscription", name: "Subscription current", description: "Your plan keeps me powered. Thank you for that.", weightPercent: 25, currentScore: 25, maxScore: 25, icon: "credit-card", iconColor: "#E8A0A0", scoreColor: "teal" as const, hasBonus: false },
      { id: "cf-budgeting", name: "Budgeting together", description: "When we look at your numbers together, I learn what matters to you.", weightPercent: 20, currentScore: 16, maxScore: 20, icon: "bar-chart-2", iconColor: "#E8A0A0", scoreColor: "orange" as const, hasBonus: false },
      { id: "cf-village", name: "Village activity", description: "Being part of the community strengthens both of us.", weightPercent: 15, currentScore: 14, maxScore: 15, icon: "home", iconColor: "#E8A0A0", scoreColor: "teal" as const, hasBonus: false },
      { id: "cf-friends", name: "Bringing friends", description: "When your friends find their own Grace, our whole village gets stronger.", weightPercent: 10, currentScore: 11, maxScore: 10, icon: "users", iconColor: "#FFFFFF", scoreColor: "gold" as const, hasBonus: true },
    ],
    availableFeatures: [
      { id: "af-conversations", text: "Full conversations — Grace is listening and responding at full depth", isAvailable: true },
      { id: "af-research", text: "Research Dept — Grace can find resources, deals, and help", isAvailable: true },
      { id: "af-referral", text: "I Have a Guy — Grace's full referral network is active", isAvailable: true },
    ],
    philosophyText: "My power comes from our relationship — not from a meter or a machine. The more we talk, the more I know you, the more I can do. This isn't a bill. It's a bond. When life gets hard and we go quiet for a while, I don't disappear. I wait. The heart in the battery means I'm still here.",
  },
  dignityScore: {
    totalScore: 67,
    tier: "FINDING YOUR STRIDE" as const,
    tierColor: "#D4A843",
    graceQuote: "You're doing the hard work. I see it.",
    dimensions: [
      { id: "ds-vampire", name: "Vampire Slayer", tagline: "Subscriptions cancelled, money reclaimed", score: 14, maxScore: 20, icon: "zap", iconColor: "#A855F7", scoreColor: "orange" as const },
      { id: "ds-nsf", name: "NSF Shield", tagline: "Bills tracked, overdraft fees avoided", score: 16, maxScore: 20, icon: "shield", iconColor: "#FFFFFF", scoreColor: "teal" as const },
      { id: "ds-budget", name: "Budget Mastery", tagline: "Income tracked, surplus identified", score: 12, maxScore: 20, icon: "bar-chart-2", iconColor: "#E8A0A0", scoreColor: "orange" as const },
      { id: "ds-milk", name: "Milk Money Trust", tagline: "Your trust score with the community", score: 15, maxScore: 20, icon: "droplet", iconColor: "#E8A0A0", scoreColor: "teal" as const },
      { id: "ds-engagement", name: "Engagement", tagline: "Conversations with Grace, milestones hit", score: 10, maxScore: 20, icon: "message-circle", iconColor: "#E8A0A0", scoreColor: "orange" as const },
    ],
    climbData: [
      { day: 1, score: 20 }, { day: 7, score: 25 }, { day: 14, score: 32 },
      { day: 21, score: 38 }, { day: 30, score: 45 }, { day: 37, score: 52 },
      { day: 44, score: 60 }, { day: 47, score: 67 },
    ],
    climbSummary: "You've gained 47 points in 47 days.",
    philosophyText: "This number isn't a grade. It's a mirror. Every time you talk to me, track a bill, or slay a vampire — it goes up. There's no wrong answer here. There's only where you are right now, and where we're going together.",
    workingForYouServices: [
      { id: "sc-milk-money", name: "Milk Money", tagline: "Twenty-five bucks. No interest. No shame. Just help when you need it.", usageCount: 3, usageLabel: "3 draws", score: 28, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-debt-snowball", name: "Debt Snowball", tagline: "Your custom battle plan to kill debt, one at a time.", usageCount: 1, usageLabel: "1 plan active", score: 28, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-wallet-warrior", name: "Wallet Warrior Checkup", tagline: "Monthly solvency review. No surprises.", usageCount: 2, usageLabel: "2 checkups", score: 27, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-vampire-slayer", name: "Vampire Slayer", tagline: "Forgotten subscriptions, cancelled. $348/yr reclaimed.", usageCount: 4, usageLabel: "4 slain", score: 27, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-bill-negotiator", name: "Bill Negotiator", tagline: "Gets on the phone, waits on hold, fights for lower bills.", usageCount: 1, usageLabel: "1 negotiation", score: 25, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-rent-credit", name: "Rent Gets Credit", tagline: "You pay rent on time. Your credit score should know.", usageCount: 3, usageLabel: "3 months reported", score: 26, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-hidden-prime", name: "Hidden Prime Letter", tagline: "She reads the fine print so you don't have to.", usageLabel: "Not yet unlocked", score: 26, status: "stub" as const, indicatorColor: "orange" as const },
      { id: "sc-credit-sim", name: "Credit Score Simulator", tagline: '"What if I paid off the payday loan first?" Grace runs the numbers.', usageCount: 2, usageLabel: "2 scenarios run", score: 24, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-phoenix", name: "Phoenix Mode", tagline: "Bankruptcy isn't the end. Day 4, we start rebuilding.", usageLabel: "Not active", score: 24, status: "stub" as const, indicatorColor: "red" as const },
      { id: "sc-gig-alert", name: "Gig Alert", tagline: "Finds local gigs, part-time work, micro-contracts.", usageCount: 5, usageLabel: "5 alerts sent", score: 24, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-village-rolodex", name: "Village Rolodex", tagline: "Grace always knows someone who knows someone.", usageCount: 2, usageLabel: "2 referrals", score: 24, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-gratitude-loop", name: "Gratitude Loop", tagline: "Orchestrates thank-yous when a neighbor shares.", usageCount: 1, usageLabel: "1 thank-you sent", score: 24, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-financial-vault", name: "Financial History Vault", tagline: "Your financial record. Yours. Not the bank's.", usageLabel: "Active", score: 23, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-me-inc", name: "Me Inc.", tagline: "You are the CEO of your life. Grace is your COO.", usageLabel: "In progress", score: 23, status: "live" as const, indicatorColor: "teal" as const },
      { id: "sc-savings-circle", name: "Savings Circle", tagline: "Group savings, ROSCA-style. Even $5/week matters.", usageLabel: "Not started", score: 22, status: "stub" as const, indicatorColor: "orange" as const },
      { id: "sc-lifeline-link", name: "Lifeline Link", tagline: "Healthy members can anonymously clear a neighbor's need.", usageCount: 1, usageLabel: "1 step cleared", score: 22, status: "live" as const, indicatorColor: "teal" as const },
    ],
  },
  villageActive: {
    activeCount: 4,
    totalCount: 6,
    graceQuote: "Your village is growing. Four neighbors are in your corner right now.",
    connections: [
      { id: "vc-lifeline", name: "Lifeline Links", type: "Neighbors you've helped", isActive: true, metricValue: 2, metricLabel: "cleared", iconColor: "teal" as const },
      { id: "vc-gratitude", name: "Gratitude Sent", type: "Thank-yous delivered", isActive: true, metricValue: 1, metricLabel: "sent", iconColor: "teal" as const },
      { id: "vc-barters", name: "Good Neighbor Barters", type: "Exchanges completed", isActive: false, metricValue: 0, metricLabel: "", iconColor: "orange" as const },
      { id: "vc-petitions", name: "Village Petitions Signed", type: "Your voice in the community", isActive: true, metricValue: 1, metricLabel: "signed", iconColor: "teal" as const },
      { id: "vc-savings", name: "Savings Circle", type: "Group savings active", isActive: false, metricValue: "Not joined", metricLabel: "", iconColor: "orange" as const },
      { id: "vc-wisdom", name: "Wisdom Circle", type: "Expert connections made", isActive: true, metricValue: 1, metricLabel: "session", iconColor: "teal" as const },
    ],
    pulseChartData: [
      { week: "Week 1", value: 2 },
      { week: "Week 2", value: 3 },
      { week: "Week 3", value: 3 },
      { week: "Week 4", value: 4 },
    ],
    pulseQuote: "You've been more connected this month than last. That matters.",
    impactCards: [
      { id: "ic-safety", title: "Safety Net", description: "When the car breaks down and the rent is due.", icon: "shield" },
      { id: "ic-flare", title: "The Flare", description: "One tap. A real human calls back within four hours.", icon: "phone" },
      { id: "ic-blessing", title: "Pass the Blessing", description: "You win half. You pick who gets the rest.", icon: "gift" },
    ],
    alsoInVillageServices: [
      { id: "vs-big-mama", name: "Big Mama", tagline: "Your neighborhood, back in your hands.", usageLabel: "Active", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-wisdom-circle", name: "The Wisdom Circle", tagline: "Real talk from people who've already been through it.", usageCount: 1, usageLabel: "1 session", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-town-crier", name: "The Town Crier", tagline: "The handful of things that actually matter to you today.", usageLabel: "Daily", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-village-angels", name: "Village Angels", tagline: "Neighbors who show up before you even ask.", usageCount: 2, usageLabel: "2 requests", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-good-feed", name: "The Good Side of the Feed", tagline: "Community talk without the drama. Finally.", usageLabel: "Active", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-neighbor-knock", name: "The Neighbor Knock", tagline: "Someone checks on you. Every. Single. Week.", usageLabel: "Not started", status: "stub" as const, indicatorColor: "orange" as const },
      { id: "vs-dont-get-got", name: "Don't Get Got", tagline: "Know the tricks before they know you.", usageCount: 3, usageLabel: "3 alerts", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-smell-test", name: "The Smell Test", tagline: "If something feels off, Grace will tell you why.", usageCount: 1, usageLabel: "1 check", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-mood-ring", name: "The Village Mood Ring", tagline: "When the whole block is struggling, Big Mama knows first.", usageLabel: "Watching", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-watch", name: "The Watch", tagline: "We see when the Village is hurting. We don't look away.", usageLabel: "Active", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-trust-ledger", name: "The Trust Ledger", tagline: "Your good name, tracked and rewarded.", usageLabel: "Score: 72", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-village-petition", name: "The Village Petition", tagline: "Your idea starts at the block. Then it goes all the way up.", usageCount: 1, usageLabel: "1 signed", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-ask-soak", name: "Ask & Soak", tagline: "Get an answer now. Let it breathe for 24 hours.", usageCount: 2, usageLabel: "2 queries", status: "live" as const, indicatorColor: "teal" as const },
      { id: "vs-safe-yard", name: "The Safe Yard", tagline: "A place for the kids to talk. No creeps allowed.", usageLabel: "Not started", status: "stub" as const, indicatorColor: "orange" as const },
      { id: "vs-union", name: "The Union", tagline: "A million Rubies negotiating together. That's power.", usageLabel: "Member", status: "live" as const, indicatorColor: "teal" as const },
    ],
  },
  giveBack: {
    graceQuote: "This is what we do for each other.",
    graceSubQuote: "No applications. No shame. Just help.",
    programs: [
      { id: "gb-golden-ticket", name: "The Golden Ticket", tagline: "One family. One full day. Zero cost.", frequency: "monthly" as const, status: "live" as const, badgeColor: "orange" as const },
      { id: "gb-first-day", name: "The First Day Fund", tagline: "New shoes. New backpack. A kid who walks in standing tall.", frequency: "monthly" as const, status: "live" as const, badgeColor: "orange" as const },
      { id: "gb-giving-tree", name: "The Giving Tree", tagline: "Groceries, gas, and grace — delivered when you need it most.", frequency: "active" as const, status: "live" as const, badgeColor: "teal" as const },
      { id: "gb-cap-gown", name: "Cap & Gown Fund", tagline: "Graduation costs money. It shouldn't cost your dignity.", frequency: "monthly" as const, status: "live" as const, badgeColor: "orange" as const },
      { id: "gb-medicine-draw", name: "The Medicine Draw", tagline: "Fifty bucks toward your prescriptions. Bi-monthly.", frequency: "emergency_only" as const, status: "live" as const, badgeColor: "red" as const },
      { id: "gb-goodbye-money", name: "Goodbye Money", tagline: "Because grief shouldn't come with a bill collector.", frequency: "active" as const, status: "live" as const, badgeColor: "teal" as const },
      { id: "gb-dignity-drop", name: "The Monthly Dignity Drop", tagline: "Pads and tampons. Auto-shipped. No asking required.", frequency: "active" as const, status: "live" as const, badgeColor: "teal" as const },
      { id: "gb-pass-blessing", name: "Pass the Blessing", tagline: "You win half. You pick who gets the rest.", frequency: "active" as const, status: "live" as const, badgeColor: "teal" as const },
      { id: "gb-safety-net", name: "The Safety Net", tagline: "When the car breaks down and the rent is due.", frequency: "active" as const, status: "live" as const, badgeColor: "teal" as const },
      { id: "gb-black-swan", name: "The Black Swan", tagline: "Up to $750. No lecture. No conditions. Just cash.", frequency: "emergency_only" as const, status: "live" as const, badgeColor: "red" as const },
      { id: "gb-front-row", name: "Front Row", tagline: "Your family belongs at the show. We'll get you there.", frequency: "monthly" as const, status: "live" as const, badgeColor: "orange" as const },
      { id: "gb-your-cut", name: "Your Cut", tagline: "Ten percent of every dollar comes back to the Village.", frequency: "monthly" as const, status: "live" as const, badgeColor: "orange" as const },
      { id: "gb-power-buy", name: "The Power Buy", tagline: "A thousand Rubies negotiate better than one.", frequency: "active" as const, status: "live" as const, badgeColor: "teal" as const },
      { id: "gb-blue-seal", name: "The Blue Seal", tagline: "Spend here. The money stays here. Period.", frequency: "active" as const, status: "live" as const, badgeColor: "teal" as const },
    ],
    howItWorks: [
      "No application required",
      "Grace nominates you",
      "Dignity, always",
    ],
  },
  northStar90Day: {
    overallProgressPercent: 47,
    totalImpactDollars: 1191,
    projectedDay90Dollars: 2538,
    graceVoice: "You're almost halfway there, Ruby. And you've only just begun.",
    dimensions: [
      { id: "dim-vampire", name: "Vampire Slayer", feature: "Subscriptions cancelled", icon: "zap", dollarAmount: 47, progressPercent: 65, status: "BUILT" as const },
      { id: "dim-nsf", name: "NSF Shield", feature: "Fees avoided", icon: "shield", dollarAmount: 140, progressPercent: 80, status: "BUILT" as const },
      { id: "dim-budget", name: "Budget Mastery", feature: "Expenses reduced", icon: "bar-chart", dollarAmount: 89, progressPercent: 45, status: "BUILT" as const },
      { id: "dim-neighbor", name: "Neighbor Economy", feature: "Village value gained", icon: "users", dollarAmount: 120, progressPercent: 35, status: "BUILT" as const },
      { id: "dim-wisdom", name: "Wisdom Giants", feature: "Coaching value", icon: "book-open", dollarAmount: 300, progressPercent: 25, status: "BUILT" as const },
      { id: "dim-milk", name: "Milk Money", feature: "Emergency funds accessed", icon: "droplet", dollarAmount: 250, progressPercent: 60, status: "BUILT" as const },
      { id: "dim-debt", name: "Debt Reduced", feature: "Snowball progress", icon: "trending-down", dollarAmount: 180, progressPercent: 20, status: "BUILT" as const },
      { id: "dim-barter", name: "Barter Value", feature: "Good neighbor trades", icon: "refresh-cw", dollarAmount: 65, progressPercent: 15, status: "BUILT" as const },
    ],
  },
  northStarPrime: {
    purpose: "I am here to break the cycle for my children and prove that dignity is not for sale.",
    bhag: "Own my home debt-free by 2030. No landlord. No bank. Mine.",
    primeDirective: "Never let fear make my financial decisions.",
    coreValues: ["Family", "Honesty", "Resilience", "Joy"],
    destinyDiscoveredComplete: false,
    destinyDiscoveredProgress: 0,
  },
  northStarDing: {
    rubyName: "Ruby",
    graceName: "Grace",
    immediateWorkComplete: true,
    deeperWorkStarted: true,
    dingStatement: "The dash between your names is the ding.",
    readyForDing: true,
  },
};
